version: '3.9'
services:
  aws_psql:
    image: postgres:alpine
    ports:
      - 5432:5432 # ${DB_PORT}:5432
    container_name: aws_psql #${DB_HOST}
    restart: always
    environment:
      - POSTGRES_USER=postgres #${DB_USERNAME}
      - POSTGRES_PASSWORD=victor123 #${DB_PASSWORD}
      - POSTGRES_DB=aws_db #${DB_DATABASE}
      - POSTGRES_INITDB_ARGS=--username=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - iff

  app:
    ports:
      - 3001:3001 #${APP_PORT}:3000
    networks:
      - iff
    container_name: aws_app
    environment:
          - DB_USERNAME=postgres #${DB_USERNAME}
          - DB_PASSWORD=victor123 #${DB_PASSWORD}
          - DB_DATABASE=aws_db #${DB_DATABASE}
          - DB_HOST=crud-db.cpp7aaqltvkn.us-east-1.rds.amazonaws.com
          #${- DB_HOST=aws_psql}
    links:
      - aws_psql
    depends_on:
      - aws_psql
    build:
      context: .
      dockerfile: Dockerfile

  pgadmin4:
    image: dpage/pgadmin4
    container_name: aws_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: victormbleite@hotmail.com #${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: 1q2w3e4r #${PGADMIN_PASSWORD}
    ports:
      - '8080:80'
    links:
      - aws_psql
    depends_on:
      - aws_psql
    networks:
      - iff

networks:
  iff:
    driver: bridge

volumes:
  pg-data:
  init:
